#!/usr/bin/env bash

out="$(dirname "$(dirname "$(realpath $0)")")/finalise"

data="'$(basename "$0")'"

for arg in "$@"; do
    c="${arg##*/pkgs/*/start/pkg/}"
    if [[ ! "$arg" = "$c" ]]; then
	arg="$c"
    fi
    data="$data '$arg'"
done

echo "$data" >> "$out"

