#!/usr/bin/env bash

out="$(dirname "$(dirname "$(realpath $0)")")/finalise"

echo -n "'$(basename "$0")'" >> "$out"

for arg in "$@"; do
    c="${arg##*/pkgs/*/start/pkg/}"
    if [[ ! "$arg" = "$c" ]]; then
	arg="$c"
    fi
    echo -n " '$arg'" >> "$out"
done

echo >> "$out"

